Repository hyperledger/caliper, pull requests merged in 2019-07, with the labels that each got.

#497 Fixed expected parameter
  packages/caliper-core/lib/monitor/monitor-docker.js
Labels: question

#508 Fix method of calculating CPU utilization for local docker containers in …
  packages/caliper-core/lib/monitor/monitor-docker.js
Labels: PR: missing DCO

#485 Enable user to specify a client gateway test
  packages/caliper-burrow/lib/burrowClientFactory.js
  packages/caliper-composer/lib/composerClientFactory.js
  packages/caliper-core/lib/client/client-util.js
  packages/caliper-core/lib/config/config-util.js
  packages/caliper-core/lib/config/default.yaml
  packages/caliper-fabric-ccp/lib/fabric.js
  packages/caliper-fabric-ccp/lib/fabricClientFactory.js
  packages/caliper-fabric-ccp/lib/fabricClientWorker.js
  packages/caliper-fabric-ccp/lib/fabricNetwork.js
  packages/caliper-fabric/lib/fabricClientFactory.js
  packages/caliper-iroha/lib/irohaClientFactory.js
  packages/caliper-sawtooth/lib/sawtoothClientFactory.js
  packages/caliper-tests-integration/scripts/run-integration-tests.sh
Labels: PR: under review, enhancement

#509 Fix the problem that caliper-local-client doesn't send transactions averagely
  packages/caliper-core/lib/client/caliper-local-client.js
Labels: PR: under review
