Repository hyperledger/caliper, pull requests merged in 2020-01, with the labels that each got.

#665 enable gui
  packages/caliper-gui-dashboard/.gitignore
  packages/caliper-gui-dashboard/README.md
  packages/caliper-gui-dashboard/package.json
  packages/caliper-gui-dashboard/public/index.html
  packages/caliper-gui-server/README.md
  packages/caliper-gui-server/app.js
  packages/caliper-gui-server/package.json
Labels: PR/under review

#677 fix bug that fisco-bcos adapter can't open network certificate file
  packages/caliper-fisco-bcos/lib/fiscoBcos.js
Labels: PR/change requested, PR/under review

#703 [Built on top of messenger PR] Split Fabric Adaptors and enable Fabric v2
  packages/caliper-burrow/lib/burrow.js
  packages/caliper-cli/lib/bind/bind.js
  packages/caliper-cli/lib/utils/cmdutils.js
  packages/caliper-core/lib/common/config/Config.js
  packages/caliper-core/lib/common/config/default.yaml
  packages/caliper-core/lib/common/core/blockchain-interface.js
  packages/caliper-core/lib/common/core/blockchain.js
  packages/caliper-core/lib/common/utils/caliper-utils.js
  packages/caliper-core/lib/master/orchestrators/worker-orchestrator.js
  packages/caliper-core/lib/worker/client/caliper-local-client.js
  packages/caliper-core/lib/worker/client/message-handler.js
  packages/caliper-ethereum/lib/ethereum.js
  packages/caliper-fabric/lib/adaptor-versions/v1/fabric-gateway-v1.js
  packages/caliper-fabric/lib/adaptor-versions/v1/fabric-v1.js
  packages/caliper-fabric/lib/adaptor-versions/v2/fabric-gateway-v2.js
  packages/caliper-fabric/lib/adaptor-versions/v2/fabric-v2.js
  packages/caliper-fabric/lib/fabric.js
  packages/caliper-fabric/lib/fabricClientWorker.js
  packages/caliper-fabric/package.json
  packages/caliper-fisco-bcos/lib/fiscoBcos.js
  packages/caliper-iroha/lib/iroha.js
  packages/caliper-sawtooth/lib/sawtooth.js
  packages/caliper-tests-integration/generator_tests/fabric/run.sh
Labels: component/fabric

#714 Fix incorrect docker charting spec
  docs/vNext/MonitorsAndObservers.md
Labels: bug

#713 Add ability to pass transient data and peer targets to a gateway tran…
  packages/caliper-core/lib/common/config/default.yaml
  packages/caliper-core/lib/worker/client/caliper-local-client.js
  packages/caliper-fabric/lib/adaptor-versions/v2/fabric-gateway-v2.js
Labels: enhancement
